### ISSUE TITLE
Is this embeddable?

### ISSUE THREAD

**Issue by nadeemja** [zhouzhuojie/hast#3]
Hi,

Forgive the possibly stupid question, but is this embeddable? 

Like embedded presentations on slideshare. (example: http://www.slideshare.net/andrewreedy/rapid-mobile-development-with-meteorjs)

**Comment by sallespro** [comment]
yes, when you get a link to a slidedeck, it will render the whole app to present the deck.

**Comment by nadeemja** [comment]
Thank you for answering me. I don't think I entirely understood. 

Will it render the whole app inside a wrapper, for example, that doesn't fill the whole screen? 

Could I do something like this: 

```
  <div style='width:400px;height:400px'> embed here </div>
```

**Comment by zhouzhuojie** [comment]
@nadeemja Of course you can embed it. But try to use the `<iframe>` tag.
For example, 

``` html
 <iframe 
         src="http://www.hast.me/hast/KWcAQ9AL4EEMb3wqR" 
         frameborder="0" width=600 height=400>
</iframe>

```

![test iframe](https://cloud.githubusercontent.com/assets/658840/9020704/da4ca1b6-37d0-11e5-9208-e28de12414c0.png)
